[tool.poetry]
name = "ada-eval"
version = "0.1.0"
description = "Simple project for evaluating LLM based tools for Ada"
authors = ["Rowan Walshe <walshe@adacore.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
dataclass-wizard = "^0.30.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.3.3"
pytest-cov = "^6.0.0"
ruff = "^0.8.1"
mypy = "^1.13.0"
mypy-gitlab-code-quality = "^1.1.0"

[tool.pytest.ini_options]
addopts = "-ra -q --cov=ada_eval --cov-report=term-missing"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
